# Generated by Django 4.2.2 on 2023-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quant', models.BigIntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=15)),
                ('corredor', models.BigIntegerField()),
                ('prateleira', models.BigIntegerField()),
                ('produto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.BigIntegerField()),
                ('nome', models.CharField(max_length=25)),
                ('cargo', models.CharField(max_length=25)),
                ('salario', models.BigIntegerField()),
                ('cargaHoraria', models.BigIntegerField()),
                ('folhaDePonto', models.BigIntegerField()),
                ('setor', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('quant', models.BigIntegerField()),
                ('desc', models.CharField(max_length=50)),
                ('preco', models.BigIntegerField()),
                ('categoria', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=50)),
                ('quant', models.BigIntegerField(max_length=50)),
            ],
        ),
    ]
