# Generated by Django 4.2.2 on 2023-06-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='quant',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='quant',
            field=models.BigIntegerField(),
        ),
    ]
